namespace: "gdrive"
name: "callback"
version: 0
address: ":5044"
repl_address: ":3132"
debug: false
registry:
  addresses: [""]
  type: 2
messaging:
  type: 1
  addresses: [""]
  durable: true
tracer:
  enable: false
  address: ""
  type: 1
resilience:
  rate_limiter:
    limit: 1000
    iplimit: 100
  circuit_breaker:
    timeout: 2500
cors:
  origins: [""]
logger:
  name: "callback-logger"
  level: 1
  color: true
worker:
  enable: true
  addresses: [""]
  max_concurrency: 5
  database: 3
oauth:
  project_id: ""
  client_id: ""
  client_secret: ""
  auth_uri: ""
  token_uri: ""
  auth_provider_x509_cert_url: ""
  redirect_uris: [""]
  javascript_origins: [""]
onlyoffice:
  builder:
    document_server_url: ""
    document_server_secret: ""
    document_server_header: ""
    gateway_url: ""
    callback_url: ""
  callback:
    max_size: 210000000000
    upload_timeout: 120
