namespace: "gdrive"
name: "auth"
version: 0
address: ":5052"
repl_address: ":5053"
debug: false
persistence:
  url: ""
  type: 1
registry:
  addresses: [""]
  type: 2
messaging:
  type: 1
  addresses: [""]
  durable: true
  ack_on_success: true
  requeue_on_error: true
  disable_auto_ack: true
tracer:
  enable: false
  address: ""
  type: 1
resilience:
  rate_limiter:
    limit: 500
  circuit_breaker:
    timeout: 2500
logger:
  name: "auth-logger"
  level: 1
  color: true
oauth:
  project_id: ""
  client_id: ""
  client_secret: ""
  auth_uri: ""
  token_uri: ""
  auth_provider_x509_cert_url: ""
  redirect_uris: [""]
  javascript_origins: [""]